//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelAddIn1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class List_From_Selection {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal List_From_Selection() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelAddIn1.List From Selection", typeof(List_From_Selection).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose where you want your list to go.
        /// </summary>
        internal static string ChooseListDestination {
            get {
                return ResourceManager.GetString("ChooseListDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Location.
        /// </summary>
        internal static string ListLocation {
            get {
                return ResourceManager.GetString("ListLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List not created..
        /// </summary>
        internal static string ListNotCreated {
            get {
                return ResourceManager.GetString("ListNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No destination chosen, list not created.
        /// </summary>
        internal static string NoDestinationChosen {
            get {
                return ResourceManager.GetString("NoDestinationChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to create a list from was selected..
        /// </summary>
        internal static string NothingToCreate {
            get {
                return ResourceManager.GetString("NothingToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;This will overwrite information:{0}{0}     Do you want to proceed?&quot;.
        /// </summary>
        internal static string OverwriteMessage {
            get {
                return ResourceManager.GetString("OverwriteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite Information.
        /// </summary>
        internal static string OverwriteTitle {
            get {
                return ResourceManager.GetString("OverwriteTitle", resourceCulture);
            }
        }
    }
}
