//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelAddIn1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UI_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelAddIn1.UI Resources", typeof(UI_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autofit Columns.
        /// </summary>
        internal static string AutofitColumns {
            get {
                return ResourceManager.GetString("AutofitColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autofit Rows.
        /// </summary>
        internal static string AutofitRows {
            get {
                return ResourceManager.GetString("AutofitRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create List From Selection.
        /// </summary>
        internal static string CreateListFromSelection {
            get {
                return ResourceManager.GetString("CreateListFromSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Page Breaks.
        /// </summary>
        internal static string DisplayPageBreaks {
            get {
                return ResourceManager.GetString("DisplayPageBreaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze Panes.
        /// </summary>
        internal static string FreezeOnActiveCell {
            get {
                return ResourceManager.GetString("FreezeOnActiveCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset Down.
        /// </summary>
        internal static string OffsetDown {
            get {
                return ResourceManager.GetString("OffsetDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset Left.
        /// </summary>
        internal static string OffsetLeft {
            get {
                return ResourceManager.GetString("OffsetLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset Right.
        /// </summary>
        internal static string OffsetRight {
            get {
                return ResourceManager.GetString("OffsetRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset Up.
        /// </summary>
        internal static string OffsetUp {
            get {
                return ResourceManager.GetString("OffsetUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R1C1 Reference Style.
        /// </summary>
        internal static string R1C1ReferenceStyle {
            get {
                return ResourceManager.GetString("R1C1ReferenceStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Freeze on ActiveCell.
        /// </summary>
        internal static string ReFreezeOnActiveCell {
            get {
                return ResourceManager.GetString("ReFreezeOnActiveCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part of your selection has only 1 Column and/or Row.
        ///You cannot further decrease the selection..
        /// </summary>
        internal static string ResizeSelection_LastRowColumnError {
            get {
                return ResourceManager.GetString("ResizeSelection_LastRowColumnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no active window. Please have a workbook open before using this functionality..
        /// </summary>
        internal static string ResizeSelection_NoActiveWindow {
            get {
                return ResourceManager.GetString("ResizeSelection_NoActiveWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No errors were found.
        /// </summary>
        internal static string SelectFormulaErrors_NoErrorsFound {
            get {
                return ResourceManager.GetString("SelectFormulaErrors_NoErrorsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structured Table References.
        /// </summary>
        internal static string StructuredTableReferences {
            get {
                return ResourceManager.GetString("StructuredTableReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextualNumbers to Numbers.
        /// </summary>
        internal static string TextualNumbersToNumbers {
            get {
                return ResourceManager.GetString("TextualNumbersToNumbers", resourceCulture);
            }
        }
    }
}
